FROM node:20-alpine as build

WORKDIR /app

COPY package.json /app

RUN npm install

COPY . /app

RUN npm cache clean --force
RUN rm -rf node_modules
RUN rm -rf .nuxt
RUN npm install
RUN npm run build

# Create a new Docker image and name it "prod"
FROM node:20-alpine as prod

WORKDIR /app

# Copy the built application from the "build" image into the "prod" image
COPY --from=build /app/.output /app/.output

# Start is the same as before
CMD ["node", ".output/server/index.mjs"]