version: '3.8'

services:
  traefik:
    image: traefik:v2.5
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik-ssl:/ssl"
    labels:
      - "traefik.enable=true"

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`app.seu-dominio.com`)"
      - "traefik.http.services.app.loadbalancer.server.port=3000"
    depends_on:
      - traefik
