// Generated by https://quicktype.io

export interface ILoginResponse {
  status: string;
  user: User;
  authorisation: IAuthorization;
}

export interface ILogin {
  login: string | null;
  password: string | null;
  remember?: boolean;
  'g-recaptcha-response'?: string | null;
}

export interface IAuthorization {
  token: string;
  type: string;
}

export interface User {
  id: number;
  guid: string;
  name: string;
  email: string;
  email_verified_at: string;
  current_team_id: null;
  profile_photo_path: null;
  created_at: string;
  updated_at: string;
  two_factor_secret: null;
  two_factor_recovery_codes: null;
  last_login_date: null;
  mqtt_pwd: null;
  mqtt_pwd_date: null;
  confirmed: boolean;
  confirmation_code: null;
  acl: number;
  old_site: null;
  old_user_id: null;
  old_type_password: number;
  username: string;
  bio: null;
  sex: null;
  country: string;
  city: string;
  language: string;
  timezone: string;
  img_path: string;
  phone: string;
}

export interface IUser {
  [x: string]: any | null;
  id: number;
  name: string;
  username: string;
  timezone: string;
  language: string;
  acl: number;
}

export interface IRegisterForm {
  username: string | null;
  email: string | null;
  password: string | null;
  password_confirmation: string | null;
  'g-recaptcha-response'?: string | null;
  name?: string;
  age: number | null;
}

export interface IResetPasswordForm {
  email: string | null;
  password: string | null;
  password_confirmation: string | null;
  token: string | null;
}
