name: Build and Push Docker Image

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          docker build -t wepray-frontend:latest -f Dockerfile.prod .
          docker tag wepray-frontend:latest ghcr.io/${{ github.repository }}/wepray-frontend:latest
          docker push ghcr.io/${{ github.repository }}/wepray-frontend:latest
